module.exports=[
  "/",
  "/doc",
  "/doc/test",
  {path:"/user/register",method:"get"},
  {path:"/user/register",method:"post"},
  "/user/login",
  '/testpost',
  '/testpost1',
  '/testpost2',
  '/testpost3',
  '/home',
  /\/wx\/door/
]